version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
  - package-ecosystem: pip
    directory: /pulumi
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
    groups:
      pulumi:
        dependency-type: "production"
      pulumi-dev:
        dependency-type: "development"
  - package-ecosystem: cargo
    directories:
      - /app
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
    groups:
      cargo:
        patterns:
          - "*"
