name: Pulumi Up
on:
  push:
    branches:
      - main
    paths:
      - pulumi/**
      - .github/workflows/pulumi-up.yml

concurrency:
  group: ghas-erfiume-pulumi-up-${{ github.ref }}

jobs:
  python-ci-pulumi:
    permissions: {}
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0
    with:
      working-directory: "./pulumi"

  pulumi-preview:
    name: Pulumi Preview
    needs: [python-ci-pulumi]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: notdodo/github-actions/.github/workflows/pulumi-preview.yml@pulumi-v0
    with:
      aws-role: arn:aws:iam::841162699174:role/erfiume-oidc-write
      aws-secrets-mapping: >
        CLOUDFLARE_API_TOKEN, erfiume-gha-cloudflare-read-write
      stack-name: notdodo/erfiume/production
      working-directory: "./pulumi"
