name: Pulumi Up
on:
  push:
    branches:
      - main
    paths:
      - pulumi/**
      - .github/workflows/pulumi-up.yml

concurrency:
  group: ghas-erfiume-pulumi-up-${{ github.ref }}

jobs:
  pulumi-up:
    name: Pulumi Up
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./pulumi
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
        with:
          persist-credentials: false
      - run: |
          echo "PULUMI_HOME=${GITHUB_WORKSPACE}/.pulumi" >> $GITHUB_ENV
          echo "POETRY_PATH=$([ -f poetry.lock ] && echo ./pulumi || realpath -s --relative-to=${GITHUB_WORKSPACE} ../)" >> $GITHUB_ENV
        working-directory: ./pulumi
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        # v5.6.0
        with:
          python-version: 3.12
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        # v4.2.3
        with:
          path: ~/.local
          key: poetry-latest
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
        # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - id: cache-deps
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        # v4.2.3
        with:
          path: |
            ${{ env.POETRY_PATH }}/.venv
            ${{ env.POETRY_PATH }}/.mypy_cache
          key: python-3.12-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            python-3.12-poetry
      - run: poetry install
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - uses: pulumi/auth-actions@1c89817aab0c66407723cdef72b05266e7376640
        # v1.0.1
        with:
          organization: notdodo
          # kics-scan ignore-line
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:notdodo
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        # v4.2.3
        with:
          path: ${{ env.PULUMI_HOME }}/plugins
          key: python-3.12-pulumi-${{ hashFiles('**/poetry.lock') }}
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        # v4.2.1
        with:
          role-to-assume: arn:aws:iam::841162699174:role/erfiume-oidc-write
          aws-region: eu-west-1
          retry-max-attempts: 2
      - uses: aws-actions/aws-secretsmanager-get-secrets@5e19ff380d035695bdd56bbad320ca535c9063f2
        # v2.0.9
        with:
          secret-ids: CLOUDFLARE_API_TOKEN, erfiume-gha-cloudflare-read-write
      - uses: pulumi/actions@df5a93ad715135263c732ba288301bd044c383c0
        # v6.3.0
        with:
          command: up
          diff: true
          stack-name: notdodo/erfiume/production
          work-dir: ./pulumi
          color: always
          suppress-progress: true
