name: Infrastructure Security Scan
on:
  push:
    branches:
      - main
    paths-ignore:
      - "/app/**/**.rs"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "/app/**/**.rs"

concurrency:
  group: ghas-infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-scan:
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@infra-scan-v0
