
[tasks.clean]
condition = { profiles = ["development"] }
command = "cargo"
args = ["clean"]

[tasks.format]
condition = { profiles = ["development"] }
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.update]
condition = { profiles = ["development"] }
install_crate = "cargo-edit"
command = "cargo"
args = ["upgrade"]

[tasks.clippy-gha]
condition = { profiles = ["gha"] }
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "--message-format=json",
    "--",
    "-D",
    "warnings",
]

[tasks.clippy-dev]
condition = { profiles = ["development"] }
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "${@}",
    "--",
    "-D",
    "warnings",
]

[tasks.check]
condition = { profiles = ["development"] }
dependencies = ["format", "test", "clippy-dev"]

[tasks.clippy]
dependencies = ["clippy-dev", "clippy-gha"]
