
[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.update]
install_crate = "cargo-edit"
command = "cargo"
args = ["upgrade"]

[tasks.clippy-ci]
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "--message-format=json",
    "--",
    "-D",
    "warnings",
]

[tasks.clippy]
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "${@}",
    "--",
    "-D",
    "warnings",
]

[tasks.check]
condition = { profiles = ["dev"] }
dependencies = ["format", "test", "clippy"]

[tasks.check-ci]
condition = { profiles = ["ci"] }
dependencies = ["clippy-ci"]
